### ISSUE TITLE
bounty: phase 1

### ISSUE THREAD

**Issue by wds4** [wds4/DCoSL#1]
Implement the [phase 1 bounty](https://github.com/wds4/DCoSL/blob/main/bounties/curatedLists/phase1/phase1.md) for curated lists. Follow the link for details, including the reward in sats.

In a nutshell: Begin the process of refactoring Curated Lists as a webapp with superb UX. 

Currently Curated Lists exists as a functioning app in the [Pretty Good Apps nostr desktop client](https://github.com/wds4/pretty-good). Phase 1 will be the first in a series of bounties to refactor this app as a web app.

Phase 1 will not be a full implementation of curated lists, but will simply allow visitors to the site to explore existing lists, list items, endorsements of list items, and endorsements of users as list curators, all of which can currently be submitted as nostr events using the desktop client. Future phases will add more functionality, including the ability to submit new lists, list items, and attestations. The actual curation itself (designation of submitted items as `accepted` or `rejected` items on the list by the reference user's web of trust) is not needed for collection of the phase 1 bounty.

**Comment by ralyodio** [comment]
is this running on the web somewhere?

**Comment by ralyodio** [comment]
also phase 1 bounty gives a 404

**Comment by wds4** [comment]
Hi @ralyodio -- not on the web yet, although I may still try to get a web app going at some point. For now I'm continuing to focus on the desktop app instead. I've put the bounties on hold and moved them into an "inactive" folder [here](https://github.com/wds4/DCoSL/tree/main/bounties) for now, although I would consider funding one if a dev were to show some interest in the project.

**Comment by wds4** [comment]
Closing this thread as this webapp is currently under development by @AntonStrickland.
